### ISSUE TITLE
yggdrasil-api result set return error

### ISSUE THREAD

**Issue by zMCdarc** [printempw/blessing-skin-plugins#1]
重现：当登陆并选择角色完成一次后，启动器再次利用access-token登录时，yggdrasil-api返回的将是没有角色。需要退出登陆，并重新输入密码获取access-token

**Comment by zMCdarc** [comment]
补充: 是在短时间内再次登陆触发 >.<

**Comment by printempw** [comment]
这个问题我昨天也发现了，试着寻找了一下原因，发现新版 HMCL 不知为何在第二次登录时只调用了 `/validate` 接口，而旧版 HMCL 与 Mojang 规范都是要求调用 `/refresh` 接口的。

说实话我也觉得很迷，不知道为什么 HMCL 要这样做（按照 wiki.vg 中定义的规范，`/validate` 在成功后是返回 `204 No Content` 的）。

解决方法：使用旧版 HMCL，至少 2.4.x 是没有这个问题的，其他版本我没测试过。

**Comment by zMCdarc** [comment]
但是我使用yushijunhun的authlib时没有出现这类问题.

**Comment by printempw** [comment]
那我也不知道为什么，我看了 yushijunhun 的 backend 实现源码，和我的并没有什么差别。

请你进行如下测试：

1. 当你在 yushijunhun 的 backend 中添加多个角色后，第一次出现角色选择界面，再次登录时也会提示无角色吗？
2. 如果你在皮肤站上**只有一个角色**，即不弹出角色选择节目直接进入游戏，下次登录时还会提示没有角色吗？

**Comment by zMCdarc** [comment]
1. 退出登录后再次登录可以选择角色
2. 貌似不会

**Comment by printempw** [comment]
退出登录？

使用 yushijunhun 的 backend 时，启动器第一次使用密码登录成功并进入角色选择界面后，第二次登录（不输入密码直接登录）的时候也可以弹出角色选择节目吗？

**Comment by zMCdarc** [comment]
如果等久一点有时候可以，有时候又还是空角色。然后如果退出游戏立马打开启动器点开始游戏，必定出空角色。

**Comment by printempw** [comment]
你说的这情况是 yushijunhun 的 backend 还是我的皮肤站插件？

**Comment by printempw** [comment]
由于本 issue 长时间没有新回复，现做关闭处理。
