### ISSUE TITLE
静态资源链接有误

### ISSUE THREAD

**Issue by g-plane** [printempw/blessing-skin-plugins#2]
https://github.com/printempw/blessing-skin-plugins/blob/5098e833f93bbc118abc52628b3a614b85162ec8/import-v2-data/views/master.tpl#L9
应为 `../../resources/assets/dist/css/install.css`

**Comment by printempw** [comment]
感谢指出。

可惜我现在人在外地，手头没有环境，你可以提交一个 Pull Request 吗？或者直接给你 Collaborator 权限？

**Comment by g-plane** [comment]
可以的。谢谢。
________________________________
